DELIMITER //

CREATE PROCEDURE pay_china_eu_deficit()
BEGIN

  DECLARE PAY_RATE decimal(3,2);
  DECLARE PAY_RESULT decimal(3,2);
  DECLARE CHINA_EU_DEFICIT decimal(18,4);
  DECLARE CHINA_EUR_SUPPLY bigint(20);
  DECLARE CHINA_EU_PAYMENT decimal(18,4);
  DECLARE EU_EUR_SUPPLY bigint(20);
  DECLARE CHINA_EU_DEFICIT_NEW decimal(18,4);

  SET PAY_RATE = 0.1;
  SET PAY_RESULT = 0.9;
  SET CHINA_EU_DEFICIT = (SELECT DEFICIT FROM S18336Pteam1.CHINA WHERE CURRENCY_ISO = 'EUR');
  SET CHINA_EUR_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.CHINA WHERE CURRENCY_ISO = 'EUR');
  SET CHINA_EU_PAYMENT = (CHINA_EU_DEFICIT * PAY_RATE);
  SET EU_EUR_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.EU WHERE CURRENCY_ISO = 'EUR');

  if CHINA_EU_DEFICIT < 0 then
    WHILE CHINA_EUR_SUPPLY < abs(CHINA_EU_PAYMENT) DO
      call generate_cny_trader(2, 'CNY', 'EUR', 1);
      call cny_eur_marketplace;
      SET CHINA_EUR_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.CHINA WHERE CURRENCY_ISO = 'EUR');
    END WHILE;
    UPDATE S18336Pteam1.CHINA SET DEFICIT = (CHINA_EU_DEFICIT * PAY_RESULT) WHERE CURRENCY_ISO = 'EUR';
    UPDATE S18336Pteam1.CHINA SET SUPPLY_OF_CURRENCY = (CHINA_EUR_SUPPLY + CHINA_EU_PAYMENT) WHERE CURRENCY_ISO = 'EUR';
    UPDATE S18336Pteam1.EU SET SUPPLY_OF_CURRENCY = (EU_EUR_SUPPLY - CHINA_EU_PAYMENT) WHERE CURRENCY_ISO = 'EUR';
    SET CHINA_EU_DEFICIT_NEW = (SELECT DEFICIT FROM S18336Pteam1.CHINA WHERE CURRENCY_ISO = 'EUR');
    UPDATE S18336Pteam1.EU SET DEFICIT = abs(CHINA_EU_DEFICIT_NEW) WHERE CURRENCY_ISO = 'CNY';
  end if;
END //

DELIMITER ;
