DELIMITER //

CREATE PROCEDURE pay_russia_china_deficit()
BEGIN

  DECLARE PAY_RATE decimal(3,2);
  DECLARE PAY_RESULT decimal(3,2);
  DECLARE RUSSIA_CHINA_DEFICIT decimal(18,4);
  DECLARE RUSSIA_CNY_SUPPLY bigint(20);
  DECLARE RUSSIA_CHINA_PAYMENT decimal(18,4);
  DECLARE CHINA_YUAN_SUPPLY bigint(20);
  DECLARE RUSSIA_CHINA_DEFICIT_NEW decimal(18,4);

  SET PAY_RATE = 0.1;
  SET PAY_RESULT = 0.9;
  SET RUSSIA_CHINA_DEFICIT = (SELECT DEFICIT FROM S18336Pteam1.RUSSIA WHERE CURRENCY_ISO = 'CNY');
  SET RUSSIA_CHINA_PAYMENT = (RUSSIA_CHINA_DEFICIT * PAY_RATE);
  SET RUSSIA_CNY_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.RUSSIA WHERE CURRENCY_ISO = 'CNY');
  SET CHINA_YUAN_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.CHINA WHERE CURRENCY_ISO = 'CNY');

  if RUSSIA_CHINA_DEFICIT < 0 then
    WHILE RUSSIA_CNY_SUPPLY < abs(RUSSIA_CHINA_PAYMENT) DO
      call generate_rub_trader(2, 'RUB', 'CNY', 1);
      call cny_rub_marketplace;
      SET RUSSIA_CNY_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.RUSSIA WHERE CURRENCY_ISO = 'CNY');
    END WHILE;
    UPDATE S18336Pteam1.RUSSIA SET DEFICIT = (RUSSIA_CHINA_DEFICIT * PAY_RESULT) WHERE CURRENCY_ISO = 'CNY';
    UPDATE S18336Pteam1.RUSSIA SET SUPPLY_OF_CURRENCY = (RUSSIA_CNY_SUPPLY + RUSSIA_CHINA_PAYMENT) WHERE CURRENCY_ISO = 'CNY';
    UPDATE S18336Pteam1.CHINA SET SUPPLY_OF_CURRENCY = (CHINA_YUAN_SUPPLY - RUSSIA_CHINA_PAYMENT) WHERE CURRENCY_ISO = 'CNY';
    SET RUSSIA_CHINA_DEFICIT_NEW = (SELECT DEFICIT FROM S18336Pteam1.RUSSIA WHERE CURRENCY_ISO = 'CNY');
    UPDATE S18336Pteam1.CHINA SET DEFICIT = abs(RUSSIA_CHINA_DEFICIT_NEW) WHERE CURRENCY_ISO = 'RUB';
  end if;
END //

DELIMITER ;
