DELIMITER //

CREATE PROCEDURE pay_russia_japan_deficit()
BEGIN

  DECLARE PAY_RATE decimal(3,2);
  DECLARE PAY_RESULT decimal(3,2);
  DECLARE RUSSIA_JAPAN_DEFICIT decimal(18,4);
  DECLARE RUSSIA_JPY_SUPPLY bigint(20);
  DECLARE RUSSIA_JAPAN_PAYMENT decimal(18,4);
  DECLARE JAPAN_JPY_SUPPLY bigint(20);
  DECLARE RUSSIA_JAPAN_DEFICIT_NEW decimal(18,4);

  SET PAY_RATE = 0.1;
  SET PAY_RESULT = 0.9;
  SET RUSSIA_JAPAN_DEFICIT = (SELECT DEFICIT FROM S18336Pteam1.RUSSIA WHERE CURRENCY_ISO = 'JPY');
  SET RUSSIA_JPY_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.RUSSIA WHERE CURRENCY_ISO = 'JPY');
  SET RUSSIA_JAPAN_PAYMENT = (RUSSIA_JAPAN_DEFICIT * PAY_RATE);
  SET JAPAN_JPY_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.JAPAN WHERE CURRENCY_ISO = 'JPY');

  if RUSSIA_JAPAN_DEFICIT < 0 then
    WHILE RUSSIA_JPY_SUPPLY < abs(RUSSIA_JAPAN_PAYMENT) DO
      call generate_rub_trader(2, 'RUB', 'JPY', 1);
      call jpy_rub_marketplace;
      SET RUSSIA_JPY_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.RUSSIA WHERE CURRENCY_ISO = 'JPY');
    END WHILE;
    UPDATE S18336Pteam1.RUSSIA SET DEFICIT = (RUSSIA_JAPAN_DEFICIT * PAY_RESULT) WHERE CURRENCY_ISO = 'JPY';
    UPDATE S18336Pteam1.RUSSIA SET SUPPLY_OF_CURRENCY = (RUSSIA_JPY_SUPPLY + RUSSIA_JAPAN_PAYMENT) WHERE CURRENCY_ISO = 'JPY';
    UPDATE S18336Pteam1.JAPAN SET SUPPLY_OF_CURRENCY = (JAPAN_JPY_SUPPLY - RUSSIA_JAPAN_PAYMENT) WHERE CURRENCY_ISO = 'JPY';
    SET RUSSIA_JAPAN_DEFICIT_NEW = (SELECT DEFICIT FROM S18336Pteam1.RUSSIA WHERE CURRENCY_ISO = 'JPY');
    UPDATE S18336Pteam1.JAPAN SET DEFICIT = abs(RUSSIA_JAPAN_DEFICIT_NEW) WHERE CURRENCY_ISO = 'RUB';
  end if;
END //

DELIMITER ;
