DELIMITER //

CREATE PROCEDURE pay_russia_usa_deficit()
BEGIN

  DECLARE PAY_RATE decimal(3,2);
  DECLARE PAY_RESULT decimal(3,2);
  DECLARE RUSSIA_USA_DEFICIT decimal(18,4);
  DECLARE RUSSIA_USD_SUPPLY bigint(20);
  DECLARE RUSSIA_USA_PAYMENT decimal(18,4);
  DECLARE USA_USD_SUPPLY bigint(20);
  DECLARE RUSSIA_USA_DEFICIT_NEW decimal(18,4);

  SET PAY_RATE = 0.1;
  SET PAY_RESULT = 0.9;
  SET RUSSIA_USA_DEFICIT = (SELECT DEFICIT FROM S18336Pteam1.RUSSIA WHERE CURRENCY_ISO = 'USD');
  SET RUSSIA_USD_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.RUSSIA WHERE CURRENCY_ISO = 'USD');
  SET RUSSIA_USA_PAYMENT = (RUSSIA_USA_DEFICIT * PAY_RATE);
  SET USA_USD_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.USA WHERE CURRENCY_ISO = 'USD');

  if RUSSIA_USA_DEFICIT < 0 then
    WHILE RUSSIA_USD_SUPPLY < abs(RUSSIA_USA_PAYMENT) DO
      call generate_rub_trader(2, 'RUB', 'USD', 1);
      call rub_usd_marketplace;
      SET RUSSIA_USD_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.RUSSIA WHERE CURRENCY_ISO = 'USD');
    END WHILE;
    UPDATE S18336Pteam1.RUSSIA SET DEFICIT = (RUSSIA_USA_DEFICIT * PAY_RESULT) WHERE CURRENCY_ISO = 'USD';
    UPDATE S18336Pteam1.RUSSIA SET SUPPLY_OF_CURRENCY = (RUSSIA_USD_SUPPLY + RUSSIA_USA_PAYMENT) WHERE CURRENCY_ISO = 'USD';
    UPDATE S18336Pteam1.USA SET SUPPLY_OF_CURRENCY = (USA_USD_SUPPLY - RUSSIA_USA_PAYMENT) WHERE CURRENCY_ISO = 'USD';
    SET RUSSIA_USA_DEFICIT_NEW = (SELECT DEFICIT FROM S18336Pteam1.RUSSIA WHERE CURRENCY_ISO = 'USD');
    UPDATE S18336Pteam1.USA SET DEFICIT = abs(RUSSIA_USA_DEFICIT_NEW) WHERE CURRENCY_ISO = 'RUB';
  end if;
END //

DELIMITER ;
