DELIMITER //

CREATE PROCEDURE pay_eu_china_deficit()
BEGIN

  DECLARE PAY_RATE decimal(3,2);
  DECLARE PAY_RESULT decimal(3,2);
  DECLARE EU_CHINA_DEFICIT decimal(18,4);
  DECLARE EU_CNY_SUPPLY bigint(20);
  DECLARE EU_CHINA_PAYMENT decimal(18,4);
  DECLARE CHINA_YUAN_SUPPLY bigint(20);
  DECLARE EU_CHINA_DEFICIT_NEW decimal(18,4);

  SET PAY_RATE = 0.1;
  SET PAY_RESULT = 0.9;
  SET EU_CHINA_DEFICIT = (SELECT DEFICIT FROM S18336Pteam1.EU WHERE CURRENCY_ISO = 'CNY');
  SET EU_CHINA_PAYMENT = (EU_CHINA_DEFICIT * PAY_RATE);
  SET EU_CNY_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.EU WHERE CURRENCY_ISO = 'CNY');
  SET CHINA_YUAN_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.CHINA WHERE CURRENCY_ISO = 'CNY');

  if EU_CHINA_DEFICIT < 0 then
    WHILE EU_CNY_SUPPLY < abs(EU_CHINA_PAYMENT) DO
      call generate_eur_trader(2, 'EUR', 'CNY', 1);
      call cny_eur_marketplace;
      SET EU_CNY_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.EU WHERE CURRENCY_ISO = 'CNY');
    END WHILE;
    UPDATE S18336Pteam1.EU SET DEFICIT = (EU_CHINA_DEFICIT * PAY_RESULT) WHERE CURRENCY_ISO = 'CNY';
    UPDATE S18336Pteam1.EU SET SUPPLY_OF_CURRENCY = (EU_CNY_SUPPLY + EU_CHINA_PAYMENT) WHERE CURRENCY_ISO = 'CNY';
    UPDATE S18336Pteam1.CHINA SET SUPPLY_OF_CURRENCY = (CHINA_YUAN_SUPPLY - EU_CHINA_PAYMENT) WHERE CURRENCY_ISO = 'CNY';
    SET EU_CHINA_DEFICIT_NEW = (SELECT DEFICIT FROM S18336Pteam1.EU WHERE CURRENCY_ISO = 'CNY');
    UPDATE S18336Pteam1.CHINA SET DEFICIT = abs(EU_CHINA_DEFICIT_NEW) WHERE CURRENCY_ISO = 'EUR';
  end if;
END //

DELIMITER ;
