DELIMITER //

CREATE PROCEDURE pay_eu_japan_deficit()
BEGIN

  DECLARE PAY_RATE decimal(3,2);
  DECLARE PAY_RESULT decimal(3,2);
  DECLARE EU_JAPAN_DEFICIT decimal(18,4);
  DECLARE EU_JPY_SUPPLY bigint(20);
  DECLARE EU_JAPAN_PAYMENT decimal(18,4);
  DECLARE JAPAN_JPY_SUPPLY bigint(20);
  DECLARE EU_JAPAN_DEFICIT_NEW decimal(18,4);

  SET PAY_RATE = 0.1;
  SET PAY_RESULT = 0.9;
  SET EU_JAPAN_DEFICIT = (SELECT DEFICIT FROM S18336Pteam1.EU WHERE CURRENCY_ISO = 'JPY');
  SET EU_JPY_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.EU WHERE CURRENCY_ISO = 'JPY');
  SET EU_JAPAN_PAYMENT = (EU_JAPAN_DEFICIT * PAY_RATE);
  SET JAPAN_JPY_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.JAPAN WHERE CURRENCY_ISO = 'JPY');

  if EU_JAPAN_DEFICIT < 0 then
    WHILE EU_JPY_SUPPLY < abs(EU_JAPAN_PAYMENT) DO
      call generate_eur_trader(2, 'EUR', 'JPY', 1);
      call eur_jpy_marketplace;
      SET EU_JPY_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.EU WHERE CURRENCY_ISO = 'JPY');
    END WHILE;
    UPDATE S18336Pteam1.EU SET DEFICIT = (EU_JAPAN_DEFICIT * PAY_RESULT) WHERE CURRENCY_ISO = 'JPY';
    UPDATE S18336Pteam1.EU SET SUPPLY_OF_CURRENCY = (EU_JPY_SUPPLY + EU_JAPAN_PAYMENT) WHERE CURRENCY_ISO = 'JPY';
    UPDATE S18336Pteam1.JAPAN SET SUPPLY_OF_CURRENCY = (JAPAN_JPY_SUPPLY - EU_JAPAN_PAYMENT) WHERE CURRENCY_ISO = 'JPY';
    SET EU_JAPAN_DEFICIT_NEW = (SELECT DEFICIT FROM S18336Pteam1.EU WHERE CURRENCY_ISO = 'JPY');
    UPDATE S18336Pteam1.JAPAN SET DEFICIT = abs(EU_JAPAN_DEFICIT_NEW) WHERE CURRENCY_ISO = 'EUR';
  end if;
END //

DELIMITER ;
