DELIMITER //

CREATE PROCEDURE pay_eu_russia_deficit()
BEGIN

  DECLARE PAY_RATE decimal(3,2);
  DECLARE PAY_RESULT decimal(3,2);
  DECLARE EU_RUSSIA_DEFICIT decimal(18,4);
  DECLARE EU_RUB_SUPPLY bigint(20);
  DECLARE EU_RUSSIA_PAYMENT decimal(18,4);
  DECLARE RUSSIA_RUB_SUPPLY bigint(20);
  DECLARE EU_RUSSIA_DEFICIT_NEW decimal(18,4);

  SET PAY_RATE = 0.1;
  SET PAY_RESULT = 0.9;
  SET EU_RUSSIA_DEFICIT = (SELECT DEFICIT FROM S18336Pteam1.EU WHERE CURRENCY_ISO = 'RUB');
  SET EU_RUB_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.EU WHERE CURRENCY_ISO = 'RUB');
  SET EU_RUSSIA_PAYMENT = (EU_RUSSIA_DEFICIT * PAY_RATE);
  SET RUSSIA_RUB_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.RUSSIA WHERE CURRENCY_ISO = 'RUB');

  if EU_RUSSIA_DEFICIT < 0 then
    WHILE EU_RUB_SUPPLY < abs(EU_RUSSIA_PAYMENT) DO
      call generate_eur_trader(2, 'EUR', 'RUB', 1);
      call eur_rub_marketplace;
      SET EU_RUB_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.EU WHERE CURRENCY_ISO = 'RUB');
    END WHILE;
    UPDATE S18336Pteam1.EU SET DEFICIT = (EU_RUSSIA_DEFICIT * PAY_RESULT) WHERE CURRENCY_ISO = 'RUB';
    UPDATE S18336Pteam1.EU SET SUPPLY_OF_CURRENCY = (EU_RUB_SUPPLY + EU_RUSSIA_PAYMENT) WHERE CURRENCY_ISO = 'RUB';
    UPDATE S18336Pteam1.RUSSIA SET SUPPLY_OF_CURRENCY = (RUSSIA_RUB_SUPPLY - EU_RUSSIA_PAYMENT) WHERE CURRENCY_ISO = 'RUB';
    SET EU_RUSSIA_DEFICIT_NEW = (SELECT DEFICIT FROM S18336Pteam1.EU WHERE CURRENCY_ISO = 'RUB');
    UPDATE S18336Pteam1.RUSSIA SET DEFICIT = abs(EU_RUSSIA_DEFICIT_NEW) WHERE CURRENCY_ISO = 'EUR';
  end if;
END //

DELIMITER ;
