DELIMITER $$
DROP PROCEDURE IF EXISTS bonds_aux $$
CREATE PROCEDURE bonds_aux(IN BASE VARCHAR(3), IN TRADE_WITH VARCHAR(3), IN RESERVE_MONEY DECIMAL(18, 2), IN AMT_SPENT DECIMAL(18, 2))
BEGIN

CALL get_country(BASE, @BASE_COUNTRY);
CALL get_country(TRADE_WITH, @TRADE_WITH_COUNTRY);

SET @BASE = BASE;
SET @TRADE_WITH = TRADE_WITH;
SET @RESERVE_MONEY = RESERVE_MONEY;
SET @AMT_SPENT = AMT_SPENT;

          SET @stmt2 = CONCAT("SET @OLD_SUPPLY_CURR_BASE = (SELECT SUPPLY_OF_CURRENCY FROM ", @BASE_COUNTRY, " WHERE CURRENCY_ISO = '", @BASE, "')");
          PREPARE stmt2 FROM @stmt2;
          EXECUTE stmt2;
          DEALLOCATE PREPARE stmt2;

          SELECT @OLD_SUPPLY_CURR_BASE;

          SET @NEW_SUPPLY_CURR_BASE = @OLD_SUPPLY_CURR_BASE + @AMT_SPENT; /* GIVE MONEY TO BASE COUNTRY*/
          SELECT @NEW_SUPPLY_CURR_BASE;

          SET @stmt3 = CONCAT("UPDATE ", @BASE_COUNTRY, " SET SUPPLY_OF_CURRENCY = ", @NEW_SUPPLY_CURR_BASE ," WHERE CURRENCY_ISO = '", @BASE, "'");
          PREPARE stmt3 FROM @stmt3;
          EXECUTE stmt3;
          DEALLOCATE PREPARE stmt3;

          SET @stmt4 = CONCAT("SET @OLD_SUPPLY_CURR_TRADE_WITH = (SELECT SUPPLY_OF_CURRENCY FROM ", @TRADE_WITH_COUNTRY, " WHERE CURRENCY_ISO = '", @BASE, "')");
          PREPARE stmt4 FROM @stmt4;
          EXECUTE stmt4;
          DEALLOCATE PREPARE stmt4;

          SELECT @OLD_SUPPLY_CURR_TRADE_WITH;


          SET @NEW_SUPPLY_CURR_TRADE_WITH =  @OLD_SUPPLY_CURR_TRADE_WITH - @AMT_SPENT;
          /* DEDUCT AMOUNT SPENT FROM THE SUPPLY_OF_CURRENCY IN TRADE_WITH_COUNTRY TABLE */
          SET @stmt5 = CONCAT("UPDATE ", @TRADE_WITH_COUNTRY, " SET SUPPLY_OF_CURRENCY = ", @NEW_SUPPLY_CURR_TRADE_WITH , " WHERE CURRENCY_ISO = '", @BASE, "'");
          PREPARE stmt5 FROM @stmt5;
          EXECUTE stmt5;
          DEALLOCATE PREPARE stmt5;
          /* ADD TO SUPPLY OF BONDS BOUGHT TO TRADE_WITH_COUNTRY TABLE */

          SET @stmt6 = CONCAT("SET @OLD_SUPPLY_BONDS = (SELECT SUPPLY_OF_BONDS FROM ", @TRADE_WITH_COUNTRY, " WHERE CURRENCY_ISO = '", @BASE, "')");
          PREPARE stmt6 FROM @stmt6;
          EXECUTE stmt6;
          DEALLOCATE PREPARE stmt6;

          SELECT @OLD_SUPPLY_BONDS;

          SET @stmt7 = CONCAT("SET @EXCHANGE_RATE = (SELECT PRICE FROM BOND_RATES WHERE COUNTRY_ISO = '", @BASE, "')");
          PREPARE stmt7 FROM @stmt7;
          EXECUTE stmt7;
          DEALLOCATE PREPARE stmt7;

          SELECT @EXCHANGE_RATE;

          SET @AMT_BONDS_BOUGHT = (@AMT_SPENT / @EXCHANGE_RATE);
          SET @NEW_SUPPLY_BONDS = @OLD_SUPPLY_BONDS + @AMT_BONDS_BOUGHT;

          SET @stmt8 = CONCAT("UPDATE ", @TRADE_WITH_COUNTRY, " SET SUPPLY_OF_BONDS = ", @NEW_SUPPLY_BONDS, " WHERE CURRENCY_ISO = '", @BASE, "'");
          PREPARE stmt8 FROM @stmt8;
          EXECUTE stmt8;
          DEALLOCATE PREPARE stmt8;

          SET @stmt9 = CONCAT("SET @OLD_SUPPLY_BONDS_BASE = (SELECT SUPPLY_OF_BONDS FROM ", @BASE_COUNTRY, " WHERE CURRENCY_ISO = '", @BASE, "')");
          PREPARE stmt9 FROM @stmt9;
          EXECUTE stmt9;
          DEALLOCATE PREPARE stmt9;

          SELECT @OLD_SUPPLY_BONDS_BASE;

          SET @NEW_SUPPLY_BONDS_BASE = @OLD_SUPPLY_BONDS_BASE - @AMT_BONDS_BOUGHT;

          SET @stmt10 = CONCAT("UPDATE ", @BASE_COUNTRY, " SET SUPPLY_OF_BONDS = ", @NEW_SUPPLY_BONDS_BASE, " WHERE CURRENCY_ISO = '", @BASE, "'");
          PREPARE stmt10 FROM @stmt10;
          EXECUTE stmt10;
          DEALLOCATE PREPARE stmt10;

END $$
DELIMITER ;
