DELIMITER $$
DROP PROCEDURE IF EXISTS buy_bond $$
CREATE PROCEDURE buy_bond(IN BASE VARCHAR(5), IN TRADE_WITH VARCHAR(5))
BEGIN
    DECLARE AMT_SPENT INT(11);
    DECLARE PERCENTAGE_SPENT DECIMAL(10,2);
    DECLARE OLD_SUPPLY_CURR_TRADE_WITH DECIMAL(18,2);
    DECLARE NEW_SUPPLY_CURR_BASE DECIMAL(18,2); /*new supply of currency for base */
    DECLARE NEW_SUPPLY_CURR_TRADE_WITH DECIMAL(18,2); /* new supply of currency trade */
    DECLARE OLD_SUPPLY_BONDS DECIMAL(18,2);
    DECLARE NEW_SUPPLY_BONDS DECIMAL(18,2);
    DECLARE OLD_SUPPLY_BONDS_BASE DECIMAL(18,2);
    DECLARE NEW_SUPPLY_BONDS_BASE DECIMAL(18,2);
    DECLARE AMT_BONDS_BOUGHT DECIMAL(18,2);


    CALL get_country(BASE, @BASE_COUNTRY);
    CALL get_country(TRADE_WITH, @TRADE_WITH_COUNTRY);

    SET @BASE = BASE;
    SET @TRADE_WITH = TRADE_WITH;
    SET @stmt1 = CONCAT("SET @RESERVE_MONEY  = (SELECT SUPPLY_OF_CURRENCY FROM ", @TRADE_WITH_COUNTRY, " WHERE CURRENCY_ISO = '", @BASE, "')");
    PREPARE stmt1 FROM @stmt1;
    EXECUTE stmt1;
    DEALLOCATE PREPARE stmt1;

    SET @PERCENTAGE_SPENT = .000001;
    SET @AMT_SPENT = @RESERVE_MONEY * @PERCENTAGE_SPENT;   /* MONEY FROM TRADE_WITH_COUNTRY SPENT TO BUY BONDS FROM BASE */

    IF @RESERVE_MONEY > 0 THEN
        call bonds_aux(@BASE, @TRADE_WITH, @RESERVE_MONEY, @AMT_SPENT);
    ELSE
    SET @AMT_SPENT = RAND() * 1000;
    SELECT @AMT_SPENT;

      WHILE @RESERVE_MONEY <= @AMT_SPENT DO
        IF @TRADE_WITH = 'CNY' THEN
          call generate_cny_trader(2, @TRADE_WITH, @BASE, 1);

        ELSEIF @TRADE_WITH = 'USD' THEN
          call generate_usd_trader(2, @TRADE_WITH, @BASE, 1);

        ELSEIF @TRADE_WITH = 'JPY' THEN
          call generate_jpy_trader(2, @TRADE_WITH, @BASE, 1);

        ELSEIF @TRADE_WITH = 'RUB' THEN
          call generate_rub_trader(2, @TRADE_WITH, @BASE, 1);

        ELSEIF @TRADE_WITH = 'EUR' THEN
          call generate_eur_trader(2, @TRADE_WITH, @BASE, 1);

        END IF;

        call marketplace(@BASE, @TRADE_WITH);

        SET @stmt11 = CONCAT("SET @RESERVE_MONEY = (SELECT SUPPLY_OF_CURRENCY FROM ", @TRADE_WITH_COUNTRY, " WHERE CURRENCY_ISO = '", BASE, "')");
        PREPARE stmt11 FROM @stmt11;
        EXECUTE stmt11;
        DEALLOCATE PREPARE stmt11;

      END WHILE;
      call bonds_aux(@BASE, @TRADE_WITH, @RESERVE_MONEY, @AMT_SPENT);


    END IF;
    END $$
    DELIMITER ;
