DELIMITER $$
DROP TRIGGER IF EXISTS change_interest_rate $$
CREATE TRIGGER change_interest_rate 
	AFTER UPDATE ON CURRENCY_EXCHANGE
	FOR EACH ROW
	BEGIN
		IF NEW.USD < (OLD.USD * 0.9) THEN
			SET @OLD_BOND_COUPON = (SELECT COUPON FROM BOND_RATES WHERE CURRENCY_ISO = 'USD');
			UPDATE BOND_RATES SET COUPON = @OLD_BOND_COUPON * 1.1;
			CALL buy_bond('USD', 'CNY');
			CALL buy_bond('USD', 'JPY');
			CALL buy_bond('USD','RUB');
			CALL buy_bond('USD', 'EUR');
		ELSEIF NEW.CNY < (OLD.CNY * 0.9) THEN
			SET @OLD_BOND_COUPON = (SELECT COUPON FROM BOND_RATES WHERE CURRENCY_ISO = 'CNY');
			UPDATE BOND_RATES SET COUPON = @OLD_BOND_COUPON * 1.1;	
			CALL buy_bond('CNY', 'USD');
			CALL buy_bond('CNY', 'JPY');
			CALL buy_bond('CNY', 'EUR');
			CALL buy_bond('CNY', 'RUB');
		ELSEIF NEW.RUB < (OLD.RUB * 0.9) THEN
			SET @OLD_BOND_COUPON = (SELECT COUPON FROM BOND_RATES WHERE CURRENCY_ISO = 'RUB');
			UPDATE BOND_RATES SET COUPON = @OLD_BOND_COUPON * 1.1;	
			CALL buy_bond('RUB', 'USD');
			CALL buy_bond('RUB', 'EUR');
			CALL buy_bond('RUB', 'CNY');
			CALL buy_bond('RUB', 'JPY');
		ELSEIF NEW.JPY < (OLD.JPY * 0.9) THEN
			SET @OLD_BOND_COUPON = (SELECT COUPON FROM BOND_RATES WHERE CURRENCY_ISO = 'JPY');
			UPDATE BOND_RATES SET COUPON = @OLD_BOND_COUPON * 1.1;	
			CALL buy_bond('JPY', 'USD');
			CALL buy_bond('JPY', 'CNY');
			CALL buy_bond('JPY', 'EUR');
			CALL buy_bond('JPY', 'RUB');
		ELSEIF NEW.EUR < (OLD.EUR * 0.9) THEN
			SET @OLD_BOND_COUPON = (SELECT COUPON FROM BOND_RATES WHERE CURRENCY_ISO = 'EUR');
			UPDATE BOND_RATES SET COUPON = @OLD_BOND_COUPON * 1.1;	
			CALL buy_bond('EUR', 'USD');
			CALL buy_bond('EUR', 'JPY');
			CALL buy_bond('EUR', 'CNY');
			CALL buy_bond('EUR', 'RUB');
		END IF;
	END $$
DELIMITER ;
