DELIMITER //

CREATE PROCEDURE pay_usa_eu_deficit()
BEGIN

  DECLARE PAY_RATE decimal(3,2);
  DECLARE PAY_RESULT decimal(3,2);
  DECLARE USA_EU_DEFICIT decimal(18,4);
  DECLARE USA_EUR_SUPPLY bigint(20);
  DECLARE USA_EU_PAYMENT decimal(18,4);
  DECLARE EU_EUR_SUPPLY bigint(20);
  DECLARE USA_EU_DEFICIT_NEW decimal(18,4);

  SET PAY_RATE = 0.1;
  SET PAY_RESULT = 0.9;
  SET USA_EU_DEFICIT = (SELECT DEFICIT FROM S18336Pteam1.USA WHERE CURRENCY_ISO = 'EUR');
  SET USA_EUR_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.USA WHERE CURRENCY_ISO = 'EUR');
  SET USA_EU_PAYMENT = (USA_EU_DEFICIT * PAY_RATE);
  SET EU_EUR_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.EU WHERE CURRENCY_ISO = 'EUR');

  if USA_EU_DEFICIT < 0 then
    WHILE USA_EUR_SUPPLY < abs(USA_EU_PAYMENT) DO
      call generate_usd_trader(2, 'USD', 'EUR', 1);
      call eur_usd_marketplace;
      SET USA_EUR_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.USA WHERE CURRENCY_ISO = 'EUR');
    END WHILE;
    UPDATE S18336Pteam1.USA SET DEFICIT = (USA_EU_DEFICIT * PAY_RESULT) WHERE CURRENCY_ISO = 'EUR';
    UPDATE S18336Pteam1.USA SET SUPPLY_OF_CURRENCY = (USA_EUR_SUPPLY + USA_EU_PAYMENT) WHERE CURRENCY_ISO = 'EUR';
    UPDATE S18336Pteam1.EU SET SUPPLY_OF_CURRENCY = (EU_EUR_SUPPLY - USA_EU_PAYMENT) WHERE CURRENCY_ISO = 'EUR';
    SET USA_EU_DEFICIT_NEW = (SELECT DEFICIT FROM S18336Pteam1.USA WHERE CURRENCY_ISO = 'EUR');
    UPDATE S18336Pteam1.EU SET DEFICIT = abs(USA_EU_DEFICIT_NEW) WHERE CURRENCY_ISO = 'USD';
  end if;
END //

DELIMITER ;
