DELIMITER //

CREATE PROCEDURE pay_usa_japan_deficit()
BEGIN

  DECLARE PAY_RATE decimal(3,2);
  DECLARE PAY_RESULT decimal(3,2);
  DECLARE USA_JAPAN_DEFICIT decimal(18,4);
  DECLARE USA_JPY_SUPPLY bigint(20);
  DECLARE USA_JAPAN_PAYMENT decimal(18,4);
  DECLARE JAPAN_JPY_SUPPLY bigint(20);
  DECLARE USA_JAPAN_DEFICIT_NEW decimal(18,4);

  SET PAY_RATE = 0.1;
  SET PAY_RESULT = 0.9;
  SET USA_JAPAN_DEFICIT = (SELECT DEFICIT FROM S18336Pteam1.USA WHERE CURRENCY_ISO = 'JPY');
  SET USA_JPY_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.USA WHERE CURRENCY_ISO = 'JPY');
  SET USA_JAPAN_PAYMENT = (USA_JAPAN_DEFICIT * PAY_RATE);
  SET JAPAN_JPY_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.JAPAN WHERE CURRENCY_ISO = 'JPY');

  if USA_JAPAN_DEFICIT < 0 then
    WHILE USA_JPY_SUPPLY < abs(USA_JAPAN_PAYMENT) DO
      call generate_usd_trader(2, 'USD', 'JPY', 1);
      call jpy_usd_marketplace;
      SET USA_JPY_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.USA WHERE CURRENCY_ISO = 'JPY');
    END WHILE;
    UPDATE S18336Pteam1.USA SET DEFICIT = (USA_JAPAN_DEFICIT * PAY_RESULT) WHERE CURRENCY_ISO = 'JPY';
    UPDATE S18336Pteam1.USA SET SUPPLY_OF_CURRENCY = (USA_JPY_SUPPLY + USA_JAPAN_PAYMENT) WHERE CURRENCY_ISO = 'JPY';
    UPDATE S18336Pteam1.JAPAN SET SUPPLY_OF_CURRENCY = (JAPAN_JPY_SUPPLY - USA_JAPAN_PAYMENT) WHERE CURRENCY_ISO = 'JPY';
    SET USA_JAPAN_DEFICIT_NEW = (SELECT DEFICIT FROM S18336Pteam1.USA WHERE CURRENCY_ISO = 'JPY');
    UPDATE S18336Pteam1.JAPAN SET DEFICIT = abs(USA_JAPAN_DEFICIT_NEW) WHERE CURRENCY_ISO = 'USD';
  end if;
END //

DELIMITER ;
