DELIMITER //

CREATE PROCEDURE pay_usa_china_deficit()
BEGIN

  DECLARE PAY_RATE decimal(3,2);
  DECLARE PAY_RESULT decimal(3,2);
  DECLARE USA_CHINA_DEFICIT decimal(18,4);
  DECLARE USA_CNY_SUPPLY bigint(20);
  DECLARE USA_CHINA_PAYMENT decimal(18,4);
  DECLARE CHINA_YUAN_SUPPLY bigint(20);
  DECLARE USA_CHINA_DEFICIT_NEW decimal(18,4);

  SET PAY_RATE = 0.1;
  SET PAY_RESULT = 0.9;
  SET USA_CHINA_DEFICIT = (SELECT DEFICIT FROM S18336Pteam1.USA WHERE CURRENCY_ISO = 'CNY');
  SET USA_CHINA_PAYMENT = (USA_CHINA_DEFICIT * PAY_RATE);
  SET USA_CNY_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.USA WHERE CURRENCY_ISO = 'CNY');
  SET CHINA_YUAN_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.CHINA WHERE CURRENCY_ISO = 'CNY');

  if USA_CHINA_DEFICIT < 0 then
    WHILE USA_CNY_SUPPLY < abs(USA_CHINA_PAYMENT) DO
      call generate_usd_trader(2, 'USD', 'CNY', 1);
      call cny_usd_marketplace;
      SET USA_CNY_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.USA WHERE CURRENCY_ISO = 'CNY');
    END WHILE;
    UPDATE S18336Pteam1.USA SET DEFICIT = (USA_CHINA_DEFICIT * PAY_RESULT) WHERE CURRENCY_ISO = 'CNY';
    UPDATE S18336Pteam1.USA SET SUPPLY_OF_CURRENCY = (USA_CNY_SUPPLY + USA_CHINA_PAYMENT) WHERE CURRENCY_ISO = 'CNY';
    UPDATE S18336Pteam1.CHINA SET SUPPLY_OF_CURRENCY = (CHINA_YUAN_SUPPLY - USA_CHINA_PAYMENT) WHERE CURRENCY_ISO = 'CNY';
    SET USA_CHINA_DEFICIT_NEW = (SELECT DEFICIT FROM S18336Pteam1.USA WHERE CURRENCY_ISO = 'CNY');
    UPDATE S18336Pteam1.CHINA SET DEFICIT = abs(USA_CHINA_DEFICIT_NEW) WHERE CURRENCY_ISO = 'USD';
  end if;
END //

DELIMITER ;
