DELIMITER //

CREATE PROCEDURE pay_japan_china_deficit()
BEGIN

  DECLARE PAY_RATE decimal(3,2);
  DECLARE PAY_RESULT decimal(3,2);
  DECLARE JAPAN_CHINA_DEFICIT decimal(18,4);
  DECLARE JAPAN_CNY_SUPPLY bigint(20);
  DECLARE JAPAN_CHINA_PAYMENT decimal(18,4);
  DECLARE CHINA_YUAN_SUPPLY bigint(20);
  DECLARE JAPAN_CHINA_DEFICIT_NEW decimal(18,4);

  SET PAY_RATE = 0.1;
  SET PAY_RESULT = 0.9;
  SET JAPAN_CHINA_DEFICIT = (SELECT DEFICIT FROM S18336Pteam1.JAPAN WHERE CURRENCY_ISO = 'CNY');
  SET JAPAN_CHINA_PAYMENT = (JAPAN_CHINA_DEFICIT * PAY_RATE);
  SET JAPAN_CNY_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.JAPAN WHERE CURRENCY_ISO = 'CNY');
  SET CHINA_YUAN_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.CHINA WHERE CURRENCY_ISO = 'CNY');

  if JAPAN_CHINA_DEFICIT < 0 then
    WHILE JAPAN_CNY_SUPPLY < abs(JAPAN_CHINA_PAYMENT) DO
      call generate_jpy_trader(2, 'JPY', 'CNY', 1);
      call cny_jpy_marketplace;
      SET JAPAN_CNY_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.JAPAN WHERE CURRENCY_ISO = 'CNY');
    END WHILE;
    UPDATE S18336Pteam1.JAPAN SET DEFICIT = (JAPAN_CHINA_DEFICIT * PAY_RESULT) WHERE CURRENCY_ISO = 'CNY';
    UPDATE S18336Pteam1.JAPAN SET SUPPLY_OF_CURRENCY = (JAPAN_CNY_SUPPLY + JAPAN_CHINA_PAYMENT) WHERE CURRENCY_ISO = 'CNY';
    UPDATE S18336Pteam1.CHINA SET SUPPLY_OF_CURRENCY = (CHINA_YUAN_SUPPLY - JAPAN_CHINA_PAYMENT) WHERE CURRENCY_ISO = 'CNY';
    SET JAPAN_CHINA_DEFICIT_NEW = (SELECT DEFICIT FROM S18336Pteam1.JAPAN WHERE CURRENCY_ISO = 'CNY');
    UPDATE S18336Pteam1.CHINA SET DEFICIT = abs(JAPAN_CHINA_DEFICIT_NEW) WHERE CURRENCY_ISO = 'JPY';
  end if;
END //

DELIMITER ;
