DELIMITER //

CREATE PROCEDURE pay_japan_usa_deficit()
BEGIN

  DECLARE PAY_RATE decimal(3,2);
  DECLARE PAY_RESULT decimal(3,2);
  DECLARE JAPAN_USA_DEFICIT decimal(18,4);
  DECLARE JAPAN_USD_SUPPLY bigint(20);
  DECLARE JAPAN_USA_PAYMENT decimal(18,4);
  DECLARE USA_USD_SUPPLY bigint(20);
  DECLARE JAPAN_USA_DEFICIT_NEW decimal(18,4);

  SET PAY_RATE = 0.1;
  SET PAY_RESULT = 0.9;
  SET JAPAN_USA_DEFICIT = (SELECT DEFICIT FROM S18336Pteam1.JAPAN WHERE CURRENCY_ISO = 'USD');
  SET JAPAN_USD_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.JAPAN WHERE CURRENCY_ISO = 'USD');
  SET JAPAN_USA_PAYMENT = (JAPAN_USA_DEFICIT * PAY_RATE);
  SET USA_USD_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.USA WHERE CURRENCY_ISO = 'USD');

  if JAPAN_USA_DEFICIT < 0 then
    WHILE JAPAN_USD_SUPPLY < abs(JAPAN_USA_PAYMENT) DO
      call generate_jpy_trader(2, 'JPY', 'USD', 1);
      call jpy_usd_marketplace;
      SET JAPAN_USD_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.JAPAN WHERE CURRENCY_ISO = 'USD');
    END WHILE;
    UPDATE S18336Pteam1.JAPAN SET DEFICIT = (JAPAN_USA_DEFICIT * PAY_RESULT) WHERE CURRENCY_ISO = 'USD';
    UPDATE S18336Pteam1.JAPAN SET SUPPLY_OF_CURRENCY = (JAPAN_USD_SUPPLY + JAPAN_USA_PAYMENT) WHERE CURRENCY_ISO = 'USD';
    UPDATE S18336Pteam1.USA SET SUPPLY_OF_CURRENCY = (USA_USD_SUPPLY - JAPAN_USA_PAYMENT) WHERE CURRENCY_ISO = 'USD';
    SET JAPAN_USA_DEFICIT_NEW = (SELECT DEFICIT FROM S18336Pteam1.JAPAN WHERE CURRENCY_ISO = 'USD');
    UPDATE S18336Pteam1.USA SET DEFICIT = abs(JAPAN_USA_DEFICIT_NEW) WHERE CURRENCY_ISO = 'JPY';
  end if;
END //

DELIMITER ;
