DELIMITER //

CREATE PROCEDURE pay_japan_russia_deficit()
BEGIN

  DECLARE PAY_RATE decimal(3,2);
  DECLARE PAY_RESULT decimal(3,2);
  DECLARE JAPAN_RUSSIA_DEFICIT decimal(18,4);
  DECLARE JAPAN_RUB_SUPPLY bigint(20);
  DECLARE JAPAN_RUSSIA_PAYMENT decimal(18,4);
  DECLARE RUSSIA_RUB_SUPPLY bigint(20);
  DECLARE JAPAN_RUSSIA_DEFICIT_NEW decimal(18,4);

  SET PAY_RATE = 0.1;
  SET PAY_RESULT = 0.9;
  SET JAPAN_RUSSIA_DEFICIT = (SELECT DEFICIT FROM S18336Pteam1.JAPAN WHERE CURRENCY_ISO = 'RUB');
  SET JAPAN_RUB_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.JAPAN WHERE CURRENCY_ISO = 'RUB');
  SET JAPAN_RUSSIA_PAYMENT = (JAPAN_RUSSIA_DEFICIT * PAY_RATE);
  SET RUSSIA_RUB_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.RUSSIA WHERE CURRENCY_ISO = 'RUB');

  if JAPAN_RUSSIA_DEFICIT < 0 then
    WHILE JAPAN_RUB_SUPPLY < abs(JAPAN_RUSSIA_PAYMENT) DO
      call generate_jpy_trader(2, 'JPY', 'RUB', 1);
      call jpy_rub_marketplace;
      SET JAPAN_RUB_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.JAPAN WHERE CURRENCY_ISO = 'RUB');
    END WHILE;
    UPDATE S18336Pteam1.JAPAN SET DEFICIT = (JAPAN_RUSSIA_DEFICIT * PAY_RESULT) WHERE CURRENCY_ISO = 'RUB';
    UPDATE S18336Pteam1.JAPAN SET SUPPLY_OF_CURRENCY = (JAPAN_RUB_SUPPLY + JAPAN_RUSSIA_PAYMENT) WHERE CURRENCY_ISO = 'RUB';
    UPDATE S18336Pteam1.RUSSIA SET SUPPLY_OF_CURRENCY = (RUSSIA_RUB_SUPPLY - JAPAN_RUSSIA_PAYMENT) WHERE CURRENCY_ISO = 'RUB';
    SET JAPAN_RUSSIA_DEFICIT_NEW = (SELECT DEFICIT FROM S18336Pteam1.JAPAN WHERE CURRENCY_ISO = 'RUB');
    UPDATE S18336Pteam1.RUSSIA SET DEFICIT = abs(JAPAN_RUSSIA_DEFICIT_NEW) WHERE CURRENCY_ISO = 'JPY';
  end if;
END //

DELIMITER ;
