DELIMITER //

CREATE PROCEDURE pay_japan_eu_deficit()
BEGIN

  DECLARE PAY_RATE decimal(3,2);
  DECLARE PAY_RESULT decimal(3,2);
  DECLARE JAPAN_EU_DEFICIT decimal(18,4);
  DECLARE JAPAN_EUR_SUPPLY bigint(20);
  DECLARE JAPAN_EU_PAYMENT decimal(18,4);
  DECLARE EU_EUR_SUPPLY bigint(20);
  DECLARE JAPAN_EU_DEFICIT_NEW decimal(18,4);

  SET PAY_RATE = 0.1;
  SET PAY_RESULT = 0.9;
  SET JAPAN_EU_DEFICIT = (SELECT DEFICIT FROM S18336Pteam1.JAPAN WHERE CURRENCY_ISO = 'EUR');
  SET JAPAN_EUR_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.JAPAN WHERE CURRENCY_ISO = 'EUR');
  SET JAPAN_EU_PAYMENT = (JAPAN_EU_DEFICIT * PAY_RATE);
  SET EU_EUR_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.EU WHERE CURRENCY_ISO = 'EUR');

  if JAPAN_EU_DEFICIT < 0 then
    WHILE JAPAN_EUR_SUPPLY < abs(JAPAN_EU_PAYMENT) DO
      call generate_jpy_trader(2, 'JPY', 'EUR', 1);
      call eur_jpy_marketplace;
      SET JAPAN_EUR_SUPPLY = (SELECT SUPPLY_OF_CURRENCY FROM S18336Pteam1.JAPAN WHERE CURRENCY_ISO = 'EUR');
    END WHILE;
    UPDATE S18336Pteam1.JAPAN SET DEFICIT = (JAPAN_EU_DEFICIT * PAY_RESULT) WHERE CURRENCY_ISO = 'EUR';
    UPDATE S18336Pteam1.JAPAN SET SUPPLY_OF_CURRENCY = (JAPAN_EUR_SUPPLY + JAPAN_EU_PAYMENT) WHERE CURRENCY_ISO = 'EUR';
    UPDATE S18336Pteam1.EU SET SUPPLY_OF_CURRENCY = (EU_EUR_SUPPLY - JAPAN_EU_PAYMENT) WHERE CURRENCY_ISO = 'EUR';
    SET JAPAN_EU_DEFICIT_NEW = (SELECT DEFICIT FROM S18336Pteam1.JAPAN WHERE CURRENCY_ISO = 'EUR');
    UPDATE S18336Pteam1.EU SET DEFICIT = abs(JAPAN_EU_DEFICIT_NEW) WHERE CURRENCY_ISO = 'JPY';
  end if;
END //

DELIMITER ;
