DELIMITER $$
DROP TRIGGER IF EXISTS change_interest_rate $$
CREATE TRIGGER change_interest_rate 
AFTER UPDATE ON CREDIT_SCORE_RATING 
FOR EACH ROW
BEGIN 
    DECLARE OLD_BOND_COUPON DECIMAL(18,2);
    IF NEW.CREDIT_SCORE_RATING < OLD.CREDIT_SCORE_RATING THEN
        SELECT COUPON INTO OLD_BOND_COUPON FROM BOND_RATES WHERE COUNTRY_ISO = OLD.CURRENCY_ISO;
        UPDATE BOND_RATES SET COUPON = OLD_BOND_COUPON * 1.1 WHERE COUNTRY_ISO = OLD.CURRENCY_ISO;
    END IF;
    
END $$
DELIMITER ;
