INSERT INTO BOND_RATES(`COUNTRY_ISO`,`COUPON`,`PRICE`) VALUES ('USD', RAND(), 100*RAND());
INSERT INTO BOND_RATES(`CURRENCY_ISO`,`COUPON`,`PRICE`) VALUES ('RUB', RAND(), 100*RAND());
INSERT INTO BOND_RATES(`CURRENCY_ISO`,`COUPON`,`PRICE`) VALUES ('EUR', RAND(), 100*RAND());
INSERT INTO BOND_RATES(`CURRENCY_ISO`,`COUPON`,`PRICE`) VALUES ('JPY', RAND(), 100*RAND());
INSERT INTO BOND_RATES(`CURRENCY_ISO`,`COUPON`,`PRICE`) VALUES ('CNY', RAND(), 100*RAND());
